baseurl: "https://shunyaueta.com/"
defaultContentLanguage: "ja"
languageCode: "ja"
title: "hurutoriya"
theme: "PaperMod"
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true

languages:
  ja:
    languageName: "Japanese"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: About
          url: about
          weight: 10
        - name: Newsletter
          url: tags/newsletter/
          weight: 10
        - name: RSS
          url: index.xml
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  homeInfoParams:
    Title: ğŸ¦… â˜ƒï¸
    Content: >
      - ä¸»ã«ã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢é–‹ç™ºã‚„æ¤œç´¢æŠ€è¡“ã€æ©Ÿæ¢°å­¦ç¿’ã«ã¤ã„ã¦è¨˜äº‹ã‚’åŸ·ç­†ã—ã¦ã„ãã¾ã™ã€‚

      - _[â†’è‘—è€…ã«ã¤ã„ã¦è©³ã—ã](/about)_
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: false
  socialIcons:
    - name: github
      url: "https://github.com/hurutoriya"
    - name: twitter
      url: "https://twitter.com/hurutoriya"
    - name: mastodon
      url: https://mstdn.jp/web/@hurutoriya
    - name: linkedin
      url: "https://www.linkedin.com/in/hurutoriya/"
    - name: buymeacoffee
      url: https://www.buymeacoffee.com/hurutoriya
    - name: rss
      url: "index.xml"
  ShowPostNavLinks: true
  author: "Shunya Ueta"
  title: "Shunya Ueta"
  description: Shunya Ueta's blog
  images:
    - ogp.jpg
  comments: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: false
    style: monokai
