baseurl: "https://shunyaueta.com/"
defaultContentLanguage: "ja"
languageCode: "ja"
title: "Shunya Ueta"
theme: "PaperMod"
paginate: 5

enableGitInfo: true
frontmatter:
  lastmod:
    - lastmod
    - :git
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: UA-39994406-11

languages:
  ja:
    languageName: "Japanese"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: About
          url: about
          weight: 10
        - name: Newsletter
          url: "https://www.getrevue.co/profile/hurutoriya"
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  titleEmoji: "ğŸ¦…"
  homeInfoParams:
    Title: Hello ğŸ‘
    Content: >
      - a.k.a @hurutoriya ğŸ¦…

      - ã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã¨ã—ã¦åƒã„ã¦ã„ã¾ã™ã€‚æ©Ÿæ¢°å­¦ç¿’ã®å®Ÿå¿œç”¨ã‚„æ¤œç´¢é ˜åŸŸã«èˆˆå‘³ãŒã‚ã‚Šã¾ã™ã€‚

      - _[â†’see more detail](/about)_
  socialIcons:
    - name: github
      url: "https://github.com/hurutoriya"
    - name: twitter
      url: "https://twitter.com/hurutoriya"
    - name: linkedin
      url: "https://www.linkedin.com/in/hurutoriya/"
    - name: rss
      url: "index.xml"
  ShowPostNavLinks: true
  author: "Shunya Ueta"
  title: "Shunya Ueta"
  description: Shunya Ueta's blog
  images:
    - ogp.jpg
  comments: true


menu:
  header:
    - name: All posts
      url: "/articles/"
    - name: Newsletter
      url: "/newsletter/"
  footer:
    - name: RSS
      url: "/index.xml"
    - name: About
      url: "/about/"
    - name: Support
      url: "https://www.buymeacoffee.com/hurutoriya"
    - name: Newsletter
      url: "/newsletter/"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: false
    style: monokai
