baseurl: "https://shunyaueta.com/"
defaultContentLanguage: "ja"
languageCode: "ja"
title: "hurutoriya"
theme: "PaperMod"
paginate: 20

enableInlineShortcodes: true
enableRobotsTXT: true

languages:
  ja:
    languageName: "Japanese"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: About
          url: about
          weight: 10
        - name: Newsletter
          url: https://searchengineeringnewsletter.substack.com/
          weight: 10
        - name: RSS
          url: index.xml
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  homeInfoParams:
    Title: ğŸ¦… ğŸŒ¸
    Content: >
      - ä¸»ã«ã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢é–‹ç™ºã‚„æ¤œç´¢æŠ€è¡“ã€æ©Ÿæ¢°å­¦ç¿’ã«ã¤ã„ã¦è¨˜äº‹ã‚’åŸ·ç­†ã—ã¦ã„ãã¾ã™ã€‚

      - _[â†’è‘—è€…ã«ã¤ã„ã¦è©³ã—ã](/about)_

      - ã¾ãŸã€æ¤œç´¢æŠ€è¡“ã§é¢ç™½ã‹ã£ãŸè¨˜äº‹ã‚’ã¾ã¨ã‚ã¦é…ä¿¡ã™ã‚‹[ãƒ‹ãƒ¥ãƒ¼ã‚¹ãƒ¬ã‚¿ãƒ¼](https://searchengineeringnewsletter.substack.com/)ã‚’é…ä¿¡ã—ã¦ã„ã¾ã™ã€‚

      - æœ€æ–°å·ã¯ã€ãƒ‹ãƒ¥ãƒ¼ã‚¹ãƒ¬ã‚¿ãƒ¼ã®è³¼èª­è€…ã®ã¿ãƒ¡ãƒ¼ãƒ«ã§é…ä¿¡ã•ã‚Œã¦å…ˆèª­ã¿ã§ãã‚‹ã®ã§ã€èˆˆå‘³ã®ã‚ã‚‹æ–¹ã¯ãœã²ã”è³¼èª­ãã ã•ã„ã€‚ç„¡æ–™ã§ã™ã€‚
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: false
  socialIcons:
    - name: github
      url: "https://github.com/hurutoriya"
    - name: twitter
      url: "https://twitter.com/hurutoriya"
    - name: mastodon
      url: https://mstdn.jp/web/@hurutoriya
    - name: linkedin
      url: "https://www.linkedin.com/in/hurutoriya/"
    - name: buymeacoffee
      url: https://www.buymeacoffee.com/hurutoriya
    - name: rss
      url: "index.xml"
  ShowPostNavLinks: true
  author: "Shunya Ueta"
  title: "Shunya Ueta"
  description: Shunya Ueta's blog
  images:
    - ogp.jpg
  comments: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: false
    style: monokai
