baseurl: "https://shunyaueta.com/"
defaultContentLanguage: "ja"
languageCode: "ja"
title: "ğŸ¦… hurutoriya"
theme: "PaperMod"
paginate: 5

enableGitInfo: true
frontmatter:
  lastmod:
    - lastmod
    - :git
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: UA-39994406-11

languages:
  ja:
    languageName: "Japanese"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: About
          url: about
          weight: 10
        - name: Newsletter
          url: "https://www.getrevue.co/profile/hurutoriya"
          weight: 10
        - name: Support
          url: "https://www.buymeacoffee.com/hurutoriya"
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  homeInfoParams:
    Title: Hello ğŸ‘
    Content: >
      - ã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã¨ã—ã¦åƒã„ã¦ã„ã¾ã™ã€‚

      - ã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢é–‹ç™ºã‚„æ©Ÿæ¢°å­¦ç¿’ã€æ¤œç´¢æŠ€è¡“ã€ãƒ‡ãƒ¼ã‚¿åˆ†æã€èª­ã‚“ã è«–æ–‡ã«ã¤ã„ã¦ä¸»ã«åŸ·ç­†ã—ã¦ã„ã¾ã™ã€‚

      - _[â†’è‘—è€…ã«ã¤ã„ã¦è©³ã—ã](/about)_
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: false
  socialIcons:
    - name: github
      url: "https://github.com/hurutoriya"
    - name: twitter
      url: "https://twitter.com/hurutoriya"
    - name: linkedin
      url: "https://www.linkedin.com/in/hurutoriya/"
    - name: buymeacoffee
      url: https://www.buymeacoffee.com/hurutoriya
    - name: rss
      url: "index.xml"
  editPost:
    URL: "https://github.com/hurutoriya/hurutoriya.github.io/tree/source/content"
    Text: "Source"
    appendFilePath: true # to append file path to Edit link
  ShowPostNavLinks: true
  author: "Shunya Ueta"
  title: "Shunya Ueta"
  description: Shunya Ueta's blog
  images:
    - ogp.jpg
  comments: true

menu:
  header:
    - name: All posts
      url: "/articles/"
    - name: Newsletter
      url: "/newsletter/"
  footer:
    - name: RSS
      url: "/index.xml"
    - name: About
      url: "/about/"
    - name: Support
      url: "https://www.buymeacoffee.com/hurutoriya"
    - name: Newsletter
      url: "/newsletter/"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: false
    style: monokai
